/**
 * wallets.ts — manager + a POOL of random depositor wallets.
 *
 * Format is the loadgen's (`NAME=address,privateKey[,apiKey,apiSecret]`) so existing habits carry
 * over. Two files because the roles differ: the manager needs API credentials (setVaultDetails and
 * vault withdrawals are authenticated REST calls), depositors need them only to withdraw — a
 * deposit is a pure on-chain approve+deposit and needs no API key at all.
 *
 * The pool is intentionally LARGER than the vault's initial depositor count. Provisioning uses the
 * first N; the churn daemon draws from the whole pool, so wallets that were never in the original
 * cohort can join later. A vault whose depositor list only ever contains the same ten addresses
 * looks synthetic; one that gains and loses depositors over days does not.
 *
 * Both files are gitignored. The loadgen commits its .env.ACCOUNTS — do not copy that.
 */
import { existsSync, readFileSync, writeFileSync, chmodSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { ethers } from "ethers";
import { config } from "./config.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MANAGER_FILE = resolve(__dirname, "../.env.MANAGER");
const DEPOSITORS_FILE = resolve(__dirname, "../.env.DEPOSITORS");

export interface Signer { name: string; address: string; privateKey: string; apiKey?: string; apiSecret?: string; }

/**
 * Deterministic derivation from POOL_MNEMONIC.
 *
 * With a mnemonic set, a strategy's manager and depositor pool are always the SAME addresses —
 * so they can be funded once, in bulk (MODE=fund), and stay funded across re-runs, container
 * rebuilds, or a lost .env.DEPOSITORS. Without one, wallets are random and each run funds fresh
 * addresses just-in-time.
 *
 * Each strategy+instance gets its own BIP-44 account index, so two strategies never derive the
 * same wallet and cross-contaminate. Index 0 of an account is the manager, 1..N the depositors.
 */
function accountIndex(strategyId: string, instance: string): number {
  let h = 2166136261;
  for (const c of `${strategyId}:${instance}`) { h ^= c.charCodeAt(0); h = Math.imul(h, 16777619); }
  return (h >>> 0) % 0x7fffffff;
}
function derive(mnemonic: string, strategyId: string, instance: string, index: number): ethers.HDNodeWallet {
  const acct = accountIndex(strategyId, instance);
  return ethers.HDNodeWallet.fromPhrase(mnemonic, undefined, `m/44'/60'/${acct}'/0/${index}`);
}
export function isDeterministic(): boolean { return Boolean(config.poolMnemonic); }

function parseFile(path: string, pattern: RegExp): Signer[] {
  if (!existsSync(path)) return [];
  const out: Signer[] = [];
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq === -1) continue;
    const name = t.slice(0, eq).trim();
    if (!pattern.test(name)) continue;
    const [address, privateKey, apiKey, apiSecret] = t.slice(eq + 1).split(",").map((x) => x?.trim());
    if (!address || !privateKey) { console.warn(`[wallets] skipping malformed entry ${name}`); continue; }
    out.push({ name, address, privateKey, apiKey: apiKey || undefined, apiSecret: apiSecret || undefined });
  }
  return out;
}

export function loadManager(generate: boolean): { signer: Signer; created: boolean } {
  const existing = parseFile(MANAGER_FILE, /^MANAGER$/i);
  if (existing.length) return { signer: existing[0], created: false };
  if (!generate) throw new Error(`No manager wallet. Provide ${MANAGER_FILE} `
    + `(MANAGER=address,privateKey,apiKey,apiSecret) or set GENERATE_WALLETS=1.`);
  const w = config.poolMnemonic
    ? derive(config.poolMnemonic, config.strategy, config.instance, 0)
    : ethers.Wallet.createRandom();
  writeFileSync(MANAGER_FILE,
    `# Generated by ikon-vaultgen. GITIGNORED — never commit.\n`
    + `# MANAGER=address,privateKey,apiKey,apiSecret\n`
    + `# API creds are needed for setVaultDetails and for market-making orders. Fill them in\n`
    + `# after registering this wallet with the exchange; provisioning works without them.\n`
    + `MANAGER=${w.address},${w.privateKey},,\n`, { mode: 0o600 });
  chmodSync(MANAGER_FILE, 0o600);
  return { signer: { name: "MANAGER", address: w.address, privateKey: w.privateKey }, created: true };
}

/**
 * Load the depositor pool, minting random wallets up to `poolSize`. Never removes or reorders
 * existing entries — index order is what ties a wallet to its provisioned deposit.
 */
export function loadDepositorPool(poolSize: number, generate: boolean): { pool: Signer[]; created: number } {
  const existing = parseFile(DEPOSITORS_FILE, /^DEPOSITOR\d+$/i);
  if (existing.length >= poolSize) return { pool: existing, created: 0 };
  if (!generate) throw new Error(`Depositor pool has ${existing.length} of ${poolSize} wallets in `
    + `${DEPOSITORS_FILE}. Set GENERATE_WALLETS=1 to mint the rest.`);
  const pool = [...existing];
  for (let i = existing.length; i < poolSize; i++) {
    const w = config.poolMnemonic
      ? derive(config.poolMnemonic, config.strategy, config.instance, i + 1)
      : ethers.Wallet.createRandom();
    pool.push({ name: `DEPOSITOR${String(i + 1).padStart(3, "0")}`, address: w.address, privateKey: w.privateKey });
  }
  writeFileSync(DEPOSITORS_FILE,
    `# Generated by ikon-vaultgen. GITIGNORED — never commit.\n`
    + `# DEPOSITORnnn=address,privateKey[,apiKey,apiSecret]\n`
    + `# Random wallets. The first N (strategy depositors.count) are seeded at provision time;\n`
    + `# the churn daemon draws from the WHOLE pool, so later entries can join as new depositors.\n`
    + `# API creds are optional and only needed for a wallet to WITHDRAW (deposits are on-chain only).\n`
    + pool.map((s) => `${s.name}=${s.address},${s.privateKey}`
        + (s.apiKey ? `,${s.apiKey},${s.apiSecret ?? ""}` : "")).join("\n") + "\n", { mode: 0o600 });
  chmodSync(DEPOSITORS_FILE, 0o600);
  return { pool, created: poolSize - existing.length };
}
